export default {
    "app.dataSources.defaultDS.entities.Entity1.logics.get":
        require("./logicsMap/app.dataSources.defaultDS.entities.Entity1.logics.get.js")
            .default,
    "app.dataSources.defaultDS.entities.Entity1.logics.create":
        require("./logicsMap/app.dataSources.defaultDS.entities.Entity1.logics.create.js")
            .default,
    "app.dataSources.defaultDS.entities.Entity1.logics.update":
        require("./logicsMap/app.dataSources.defaultDS.entities.Entity1.logics.update.js")
            .default,
    "app.dataSources.defaultDS.entities.Entity1.logics.delete":
        require("./logicsMap/app.dataSources.defaultDS.entities.Entity1.logics.delete.js")
            .default,
    "app.dataSources.defaultDS.entities.Entity1.logics.createOrUpdate":
        require("./logicsMap/app.dataSources.defaultDS.entities.Entity1.logics.createOrUpdate.js")
            .default,
    "app.dataSources.defaultDS.entities.Entity1.logics.updateBy":
        require("./logicsMap/app.dataSources.defaultDS.entities.Entity1.logics.updateBy.js")
            .default,
    "app.dataSources.defaultDS.entities.Entity1.logics.deleteBy":
        require("./logicsMap/app.dataSources.defaultDS.entities.Entity1.logics.deleteBy.js")
            .default,
    "app.dataSources.defaultDS.entities.Entity1.logics.batchCreate":
        require("./logicsMap/app.dataSources.defaultDS.entities.Entity1.logics.batchCreate.js")
            .default,
    "app.dataSources.defaultDS.entities.Entity1.logics.batchUpdate":
        require("./logicsMap/app.dataSources.defaultDS.entities.Entity1.logics.batchUpdate.js")
            .default,
    "app.dataSources.defaultDS.entities.Entity1.logics.batchDelete":
        require("./logicsMap/app.dataSources.defaultDS.entities.Entity1.logics.batchDelete.js")
            .default,
    "app.dataSources.defaultDS.entities.Entity1.logics.import":
        require("./logicsMap/app.dataSources.defaultDS.entities.Entity1.logics.import.js")
            .default,
    "app.logics.loadPrintTableView1":
        require("./logicsMap/app.logics.loadPrintTableView1.js").default,
    "app.logics.loadFirstTableView3":
        require("./logicsMap/app.logics.loadFirstTableView3.js").default,
    "app.logics.loadSecondTableView3":
        require("./logicsMap/app.logics.loadSecondTableView3.js").default,
    "app.logics.loadSecondTableView2":
        require("./logicsMap/app.logics.loadSecondTableView2.js").default,
    "app.logics.loadFirstTableView1":
        require("./logicsMap/app.logics.loadFirstTableView1.js").default,
    "app.logics.loadDemo1TableView1":
        require("./logicsMap/app.logics.loadDemo1TableView1.js").default,
    "app.logics.logic1g": require("./logicsMap/app.logics.logic1g.js").default,
    "app.logics.logic2": require("./logicsMap/app.logics.logic2.js").default,
    "app.logics.loadRightmouseTableView1":
        require("./logicsMap/app.logics.loadRightmouseTableView1.js").default,
    "app.logics.loadDemoTableView2":
        require("./logicsMap/app.logics.loadDemoTableView2.js").default,
    "app.logics.logic1": require("./logicsMap/app.logics.logic1.js").default,
    "app.logics.loadDemoTableView1":
        require("./logicsMap/app.logics.loadDemoTableView1.js").default,
    "extensions.lcap_auth.logics.getUser":
        require("./logicsMap/extensions.lcap_auth.logics.getUser.js").default,
    "extensions.lcap_auth.logics.createToken":
        require("./logicsMap/extensions.lcap_auth.logics.createToken.js")
            .default,
    "extensions.lcap_auth.logics.removeToken":
        require("./logicsMap/extensions.lcap_auth.logics.removeToken.js")
            .default,
    "extensions.lcap_permission.logics.uploadResource":
        require("./logicsMap/extensions.lcap_permission.logics.uploadResource.js")
            .default,
    "extensions.lcap_permission.logics.checkPermission":
        require("./logicsMap/extensions.lcap_permission.logics.checkPermission.js")
            .default,
    "extensions.lcap_permission.logics.getUserResources":
        require("./logicsMap/extensions.lcap_permission.logics.getUserResources.js")
            .default,
    "connector.generic_s3_file_connector.testLogic":
        require("./logicsMap/connector.generic_s3_file_connector.testLogic.js")
            .default,
};
