<template>
  <u-linear-layout
    :ref="`uLinearLayout1`"
    :class="`cw-style-height`"
    :type="`root`"
    :gap="`none`"
    style="--cw-style-height: 100%; height: 100%; --custom-start: auto; min-height: 200px"
  >
    <u-router-view :ref="`router_view1`"></u-router-view>
    <u-collapse :ref="`collapse_1`">
      <u-collapse-item :ref="`collapse_item_1`">
        <template
          #title
          :ref="`template_1`"
        >
          <u-text
            :ref="`text_1`"
            :text="`选项卡——保留滚动功能和左右两侧图标按钮，隐藏滚动条`"
          ></u-text>
        </template>
        <u-tabs
          :ref="`tabs_1`"
          titleField=""
          valueField=""
          urlField=""
          closableField=""
          :appear="`capsule`"
        >
          <u-tab
            :ref="`tab_1`"
            :value="`A`"
          >
            <template
              #title
              :ref="`template_4`"
            >
              <u-text
                :ref="`text_7`"
                :text="`选项卡A`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_8`"
              :text="`选项卡 A 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_2`"
            :value="`B`"
          >
            <template
              #title
              :ref="`template_5`"
            >
              <u-text
                :ref="`text_9`"
                :text="`选项卡B`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_10`"
              :text="`选项卡 B 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_3`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_6`"
            >
              <u-text
                :ref="`text_11`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_12`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_4`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_10`"
            >
              <u-text
                :ref="`text_14`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_13`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_5`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_11`"
            >
              <u-text
                :ref="`text_16`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_15`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_6`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_12`"
            >
              <u-text
                :ref="`text_18`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_17`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_7`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_13`"
            >
              <u-text
                :ref="`text_20`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_19`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_8`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_14`"
            >
              <u-text
                :ref="`text_22`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_21`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_9`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_15`"
            >
              <u-text
                :ref="`text_24`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_23`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_18`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_24`"
            >
              <u-text
                :ref="`text_42`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_41`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_17`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_23`"
            >
              <u-text
                :ref="`text_40`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_39`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_16`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_22`"
            >
              <u-text
                :ref="`text_38`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_37`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_15`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_21`"
            >
              <u-text
                :ref="`text_36`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_35`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_14`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_20`"
            >
              <u-text
                :ref="`text_34`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_33`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_13`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_19`"
            >
              <u-text
                :ref="`text_32`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_31`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_12`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_18`"
            >
              <u-text
                :ref="`text_30`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_29`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_11`"
            :value="`B`"
          >
            <template
              #title
              :ref="`template_17`"
            >
              <u-text
                :ref="`text_28`"
                :text="`选项卡B`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_27`"
              :text="`选项卡 B 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_10`"
            :value="`A`"
          >
            <template
              #title
              :ref="`template_16`"
            >
              <u-text
                :ref="`text_26`"
                :text="`选项卡A`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_25`"
              :text="`选项卡 A 的内容`"
            ></u-text>
          </u-tab>
          <template
            #extra
            :ref="`template_7`"
          ></template>
          <template
            #title="current"
            :ref="`template_8`"
          ></template>
          <template
            #content="current"
            :ref="`template_9`"
          ></template>
        </u-tabs>
        <u-tabs
          :ref="`tabs_2`"
          :class="` cw-css-rule-tabs_2___01h3is80`"
          titleField=""
          valueField=""
          urlField=""
          closableField=""
          :appear="`capsule`"
        >
          <u-tab
            :ref="`tab_19`"
            :value="`A`"
          >
            <template
              #title
              :ref="`template_31`"
            >
              <u-text
                :ref="`text_63`"
                :text="`选项卡A`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_45`"
              :text="`选项卡 A 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_20`"
            :value="`B`"
          >
            <template
              #title
              :ref="`template_32`"
            >
              <u-text
                :ref="`text_64`"
                :text="`选项卡B`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_46`"
              :text="`选项卡 B 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_21`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_33`"
            >
              <u-text
                :ref="`text_65`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_47`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_22`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_34`"
            >
              <u-text
                :ref="`text_66`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_48`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_23`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_35`"
            >
              <u-text
                :ref="`text_67`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_49`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_24`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_36`"
            >
              <u-text
                :ref="`text_68`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_50`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_25`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_37`"
            >
              <u-text
                :ref="`text_69`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_51`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_26`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_38`"
            >
              <u-text
                :ref="`text_70`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_52`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_27`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_39`"
            >
              <u-text
                :ref="`text_71`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_53`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_28`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_40`"
            >
              <u-text
                :ref="`text_72`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_54`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_29`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_41`"
            >
              <u-text
                :ref="`text_73`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_55`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_30`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_42`"
            >
              <u-text
                :ref="`text_74`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_56`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_31`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_43`"
            >
              <u-text
                :ref="`text_75`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_57`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_32`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_44`"
            >
              <u-text
                :ref="`text_76`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_58`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_33`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_45`"
            >
              <u-text
                :ref="`text_77`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_59`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_34`"
            :value="`C`"
          >
            <template
              #title
              :ref="`template_46`"
            >
              <u-text
                :ref="`text_78`"
                :text="`选项卡C`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_60`"
              :text="`选项卡 C 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_35`"
            :value="`B`"
          >
            <template
              #title
              :ref="`template_47`"
            >
              <u-text
                :ref="`text_79`"
                :text="`选项卡B`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_61`"
              :text="`选项卡 B 的内容`"
            ></u-text>
          </u-tab>
          <u-tab
            :ref="`tab_36`"
            :value="`A`"
          >
            <template
              #title
              :ref="`template_48`"
            >
              <u-text
                :ref="`text_80`"
                :text="`选项卡A`"
              ></u-text>
            </template>
            <u-text
              :ref="`text_62`"
              :text="`选项卡 A 的内容`"
            ></u-text>
          </u-tab>
          <template
            #extra
            :ref="`template_28`"
          ></template>
          <template
            #title="current"
            :ref="`template_29`"
          ></template>
          <template
            #content="current"
            :ref="`template_30`"
          ></template>
        </u-tabs>
      </u-collapse-item>
      <u-collapse-item :ref="`collapse_item_2`">
        <template
          #title
          :ref="`template_2`"
        >
          <u-text
            :ref="`text_3`"
            :text="`多选组——使用数据源的状态下使其中一个选项禁用`"
          ></u-text>
        </template>
        <u-checkboxes
          :ref="`checkboxes_1`"
          valueField=""
          :dataSource="[`选项1`, `选项2`, `选项3`, `选项4`, `选项5`, `选项6`, `选项7`]"
          v-dependencies.reload="[]"
        >
          <template
            #item="current"
            :ref="`template_25`"
          >
            <u-text
              :ref="`text_44_${(current || {}).__nodeKey || (current || {}).index}`"
              :text="$utils['ToString']('nasl.core.String', (current || {}).item)"
            ></u-text>
          </template>
          <template
            #checkAll
            :ref="`template_26`"
          ></template>
        </u-checkboxes>
      </u-collapse-item>
    </u-collapse>
  </u-linear-layout>
</template>
<script>
export default {
  name: '/componentExtraFunction',
  mixins: [
    window.$mixins
      .enhancedCss(`:where(.cw-css-rule-tabs_2___01h3is80)[class*=u-tabs___][appear=square]>[class*=u-tabs_head___], :where(.cw-css-rule-tabs_2___01h3is80)[class*=u-tabs___][appear=round]>[class*=u-tabs_head___], :where(.cw-css-rule-tabs_2___01h3is80)[class*=u-tabs___][appear=line]>[class*=u-tabs_head___] {
  scrollbar-width: none;
  ms-overflow-style: none;
  overflow-x: auto;
}
:where(.cw-css-rule-tabs_2___01h3is80)[class*=u-tabs___] [class*=u-tabs_scroll___] {
  scrollbar-width: none;
  ms-overflow-style: none;
  overflow-x: auto;
}
`),
    window.$mixins.dataSourceUtils(),
  ],
  data() {
    return {};
  },
  meta: {
    title: '组件额外功能',
    crumb: undefined,
    crumbI18n: undefined,
    first: undefined,
    auth: undefined,
  },
  methods: {
    onSyncState(elem, key, val) {
      this[`${elem}_state_${key}`] = val;
    },
  },
};
</script>
