import Vue from 'vue';
import { installComponents } from '@vusion/utils';

require('@lcap/pc-ui/dist-theme');
require('@lcap/pc-ui/dist-theme/index.css');
import * as gx_gis_lib from 'gx_gis_lib/dist-theme';
import * as gx_chat_lib from 'gx_chat_lib/dist-theme';
import * as make_img_and_qr_code from 'make_img_and_qr_code/dist-theme';
import * as cw_verifycode_library from 'cw_verifycode_library/dist-theme';
import * as gx_clappr_lib from 'gx_clappr_lib/dist-theme';
import * as cw_echarts_library from 'cw_echarts_library/dist-theme';
import * as gx_trans_lib from 'gx_trans_lib/dist-theme';
import * as hg_cache_lib from 'hg_cache_lib/dist-theme';
import * as xh_calendar_lib from 'xh_calendar_lib/dist-theme';
import * as hg_make_pdf_lib from 'hg_make_pdf_lib/dist-theme';
import * as hg_relation_map from 'hg_relation_map/dist-theme';
import * as gx_ant_lib from 'gx_ant_lib/dist-theme';
import * as gx_qiankun_lib from 'gx_qiankun_lib/dist-theme';
import * as cw_global_loading from 'cw_global_loading/dist-theme';
import * as gx_socket from 'gx_socket/dist-theme';
import * as hg_print_lib from 'hg_print_lib/dist-theme';
import 'gx_gis_lib/dist-theme/index.css';
import 'gx_chat_lib/dist-theme/index.css';
import 'gx_clappr_lib/dist-theme/index.css';
import 'gx_trans_lib/dist-theme/index.css';
import 'xh_calendar_lib/dist-theme/index.css';
import 'hg_make_pdf_lib/dist-theme/index.css';
import 'hg_relation_map/dist-theme/index.css';
import 'gx_ant_lib/dist-theme/index.css';
import 'gx_qiankun_lib/dist-theme/index.css';
import 'hg_print_lib/dist-theme/index.css';
installComponents(Vue, gx_gis_lib);
installComponents(Vue, gx_chat_lib);
installComponents(Vue, make_img_and_qr_code);
installComponents(Vue, cw_verifycode_library);
installComponents(Vue, gx_clappr_lib);
installComponents(Vue, cw_echarts_library);
installComponents(Vue, gx_trans_lib);
installComponents(Vue, hg_cache_lib);
installComponents(Vue, xh_calendar_lib);
installComponents(Vue, hg_make_pdf_lib);
installComponents(Vue, hg_relation_map);
installComponents(Vue, gx_ant_lib);
installComponents(Vue, gx_qiankun_lib);
installComponents(Vue, cw_global_loading);
installComponents(Vue, gx_socket);
installComponents(Vue, hg_print_lib);
