export default {
    concept: "Entity",
    name: "Entity1",
    uuid: "ac2c88aebbe9497caf92c31efa34058b",
    tableName: "entity1",
    description: null,
    origin: "ide",
    changedTime: 1757126530825,
    composedBy: null,
    sharedScope: null,
    properties: [
        {
            concept: "EntityProperty",
            name: "id",
            uuid: "44c0525b692b445dacf9f6cf09b20bca",
            columnName: "id",
            label: "主键",
            description: "主键",
            required: true,
            primaryKey: true,
            relationNamespace: null,
            relationEntity: null,
            relationProperty: null,
            deleteRule: null,
            display: {
                inTable: false,
                inFilter: false,
                inForm: false,
                inDetail: false,
            },
            rules: [],
            generationRule: "auto",
            sequence: "Entity16749138985",
            changedTime: null,
            composedBy: null,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "Long",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            databaseTypeAnnotation: null,
            defaultValue: null,
            defaultCode: {},
        },
        {
            concept: "EntityProperty",
            name: "createdTime",
            uuid: "dbb89995c83f4f7e94e52972e59f9b54",
            columnName: "created_time",
            label: "创建时间",
            description: "创建时间",
            required: false,
            primaryKey: false,
            relationNamespace: null,
            relationEntity: null,
            relationProperty: null,
            deleteRule: null,
            display: {
                inTable: true,
                inFilter: false,
                inForm: false,
                inDetail: false,
            },
            rules: [],
            generationRule: "auto",
            sequence: null,
            changedTime: null,
            composedBy: null,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "DateTime",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            databaseTypeAnnotation: null,
            defaultValue: null,
            defaultCode: {},
        },
        {
            concept: "EntityProperty",
            name: "updatedTime",
            uuid: "725611f54ad34610975eea4fc7320c58",
            columnName: "updated_time",
            label: "更新时间",
            description: "更新时间",
            required: false,
            primaryKey: false,
            relationNamespace: null,
            relationEntity: null,
            relationProperty: null,
            deleteRule: null,
            display: {
                inTable: true,
                inFilter: false,
                inForm: false,
                inDetail: false,
            },
            rules: [],
            generationRule: "auto",
            sequence: null,
            changedTime: null,
            composedBy: null,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "DateTime",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            databaseTypeAnnotation: null,
            defaultValue: null,
            defaultCode: {},
        },
        {
            concept: "EntityProperty",
            name: "createdBy",
            uuid: "afeaeda1fd2a4b5f959cc5472ec07004",
            columnName: "created_by",
            label: "创建者",
            description: "创建者",
            required: false,
            primaryKey: false,
            relationNamespace: null,
            relationEntity: null,
            relationProperty: null,
            deleteRule: null,
            display: {
                inTable: false,
                inFilter: false,
                inForm: false,
                inDetail: false,
            },
            rules: [],
            generationRule: "auto",
            sequence: null,
            changedTime: null,
            composedBy: null,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "String",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            databaseTypeAnnotation: null,
            defaultValue: null,
            defaultCode: {},
        },
        {
            concept: "EntityProperty",
            name: "updatedBy",
            uuid: "03012335487343e682e88d5a67498cef",
            columnName: "updated_by",
            label: "更新者",
            description: "更新者",
            required: false,
            primaryKey: false,
            relationNamespace: null,
            relationEntity: null,
            relationProperty: null,
            deleteRule: null,
            display: {
                inTable: false,
                inFilter: false,
                inForm: false,
                inDetail: false,
            },
            rules: [],
            generationRule: "auto",
            sequence: null,
            changedTime: null,
            composedBy: null,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "String",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            databaseTypeAnnotation: null,
            defaultValue: null,
            defaultCode: {},
        },
        {
            concept: "EntityProperty",
            name: "property1",
            uuid: "c28baff01dbe480c93f2d37aa4084a33",
            columnName: "property1",
            label: null,
            description: null,
            required: false,
            primaryKey: false,
            relationNamespace: null,
            relationEntity: null,
            relationProperty: null,
            deleteRule: null,
            display: {
                inTable: true,
                inFilter: true,
                inForm: true,
                inDetail: true,
            },
            rules: [],
            generationRule: "manual",
            sequence: null,
            changedTime: 1757126532533,
            composedBy: null,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "String",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            databaseTypeAnnotation: null,
            defaultValue: null,
            defaultCode: {},
        },
        {
            concept: "EntityProperty",
            name: "property2",
            uuid: "92186d2f17f6471eaf5848d636592067",
            columnName: "property2",
            label: null,
            description: null,
            required: false,
            primaryKey: false,
            relationNamespace: null,
            relationEntity: null,
            relationProperty: null,
            deleteRule: null,
            display: {
                inTable: true,
                inFilter: true,
                inForm: true,
                inDetail: true,
            },
            rules: [],
            generationRule: "manual",
            sequence: null,
            changedTime: 1757126532923,
            composedBy: null,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "String",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            databaseTypeAnnotation: null,
            defaultValue: null,
            defaultCode: {},
        },
        {
            concept: "EntityProperty",
            name: "userName",
            uuid: "475bbfd697d84ba0a894744dbe193bda",
            columnName: "user_name",
            label: null,
            description: null,
            required: false,
            primaryKey: false,
            relationNamespace: null,
            relationEntity: null,
            relationProperty: null,
            deleteRule: null,
            display: {
                inTable: true,
                inFilter: true,
                inForm: true,
                inDetail: true,
            },
            rules: [],
            generationRule: "manual",
            sequence: null,
            changedTime: 1757126956340,
            composedBy: null,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "String",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            databaseTypeAnnotation: null,
            defaultValue: null,
            defaultCode: {},
        },
        {
            concept: "EntityProperty",
            name: "code",
            uuid: "2dc89663d93c4e33a536ae7f1ed0a7fc",
            columnName: "code",
            label: "",
            description: null,
            required: false,
            primaryKey: false,
            relationNamespace: null,
            relationEntity: null,
            relationProperty: null,
            deleteRule: null,
            display: {
                inTable: true,
                inFilter: true,
                inForm: true,
                inDetail: true,
            },
            rules: [],
            generationRule: "manual",
            sequence: null,
            changedTime: 1757320485420,
            composedBy: null,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "String",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            databaseTypeAnnotation: null,
            defaultValue: null,
            defaultCode: {},
        },
        {
            concept: "EntityProperty",
            name: "name",
            uuid: "6174d5a40309428ea5b4ef8d2a111213",
            columnName: "name",
            label: null,
            description: null,
            required: false,
            primaryKey: false,
            relationNamespace: null,
            relationEntity: null,
            relationProperty: null,
            deleteRule: null,
            display: {
                inTable: true,
                inFilter: true,
                inForm: true,
                inDetail: true,
            },
            rules: [],
            generationRule: "manual",
            sequence: null,
            changedTime: 1757320484698,
            composedBy: null,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "String",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            databaseTypeAnnotation: null,
            defaultValue: null,
            defaultCode: {},
        },
    ],
    indexes: [],
    applyAnnotations: null,
};
