export default {
    concept: "Structure",
    name: "Tree",
    description: null,
    changedTime: 1767016505725,
    typeParams: [],
    properties: [
        {
            concept: "StructureProperty",
            name: "id",
            label: null,
            description: null,
            jsonName: null,
            changedTime: 1767016513232,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "String",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            defaultValue: null,
            defaultCode: {},
        },
        {
            concept: "StructureProperty",
            name: "name",
            label: null,
            description: null,
            jsonName: null,
            changedTime: 1767016519724,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "String",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            defaultValue: null,
            defaultCode: {},
        },
        {
            concept: "StructureProperty",
            name: "parentId",
            label: null,
            description: null,
            jsonName: null,
            changedTime: 1767016532343,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "primitive",
                typeNamespace: "nasl.core",
                typeName: "String",
                inferred: false,
                ruleMap: {},
                typeArguments: [],
                returnType: [],
                properties: [],
            },
            defaultValue: null,
            defaultCode: {},
        },
        {
            concept: "StructureProperty",
            name: "children",
            label: null,
            description: null,
            jsonName: null,
            changedTime: 1767016547248,
            typeAnnotation: {
                concept: "TypeAnnotation",
                typeKind: "generic",
                typeNamespace: "nasl.collection",
                typeName: "List",
                inferred: false,
                ruleMap: {},
                typeArguments: [
                    {
                        concept: "TypeAnnotation",
                        typeKind: "reference",
                        typeNamespace: "app.structures",
                        typeName: "Tree",
                        inferred: false,
                        ruleMap: {},
                        typeArguments: [],
                        returnType: [],
                        properties: [],
                    },
                ],
                returnType: [],
                properties: [],
            },
            defaultValue: null,
            defaultCode: {},
        },
    ],
};
